apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-api
    app.kubernetes.io/component: spring-boot-api
    app.kubernetes.io/instance: spring-boot-api
    app.kubernetes.io/part-of: spring-boot-api-app
  name: spring-boot-api
spec:
  ports:
  - name: 80-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-api
    deploymentconfig: spring-boot-api
  sessionAffinity: None
  type: ClusterIP