kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-api
spec:
  template:
    spec:
      containers:
        - name: spring-boot-api
          image: ghcr.io/middlewaregruppen/spring-boot-demo-api:1
