apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-boot-api-dev
bases:
- ../../base

resources:
- namespace.yaml
- service-monitor.yaml

patchesStrategicMerge:
- sizing.yaml
- image.yaml