name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-flight:
    runs-on: ubuntu-latest
    outputs:
      pathnames: ${{ steps.prtrickery.outputs.paths }}
      numfiles: ${{ steps.prtrickery.outputs.numfiles }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: get list of files changed
      id: prtrickery
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
        echo "Files involved in the change:"
        for f in $FILES
        do 
          echo "HELLO: $f"
        done
        echo "::set-output name=paths::$(echo $FILES)"
        echo "::set-output name=numfiles::$(echo ${#FILES[@]})"
      shell: bash

  test:
    runs-on: ubuntu-latest
    needs: pre-flight
    steps:
    - uses: actions/checkout@v2

    - name: Checking...
      run: |
        echo "There are ${{ needs.pre-flight.outputs.numfiles }} files in the PR"
        echo ${{ needs.pre-flight.outputs.pathnames }}


    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run Unit Tests
      run: mvn --batch-mode --update-snapshots verify

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Build Jar
      run: mvn --batch-mode --update-snapshots clean package
